// A dictionary of epidemiology terms and their definitions, converted from the Python bot.
const KNOWLEDGE_BASE = {
      "absolute risk": "The probability of an event occurring in a specific group over a period (Chapter 12, p. 254).",
    "absolute risk reduction": "The difference in event rates between control and intervention groups, often used in clinical trials (Chapter 10, p. 213).",
    "accuracy": "The degree to which a measurement or estimate represents the true value of the attribute being measured (Chapter 5, p. 94).",
    "active immunity": "Resistance developed in response to an antigen (infecting agent or vaccine), characterized by antibody production by the host (Chapter 2, p. 35).",
    "active surveillance": "A surveillance system where public health authorities actively seek out disease cases, often through direct contact with providers (Chapter 3, p. 57).",
    "adjusted odds ratio": "An odds ratio adjusted for confounders using statistical methods like logistic regression (Chapter 12, p. 256).",
    "adjusted rate": "A rate statistically modified to remove the effect of a confounding factor, e.g., age-adjusted mortality rate (Chapter 4, p. 94).",
    "age distribution": "The proportion of a population in different age groups, affecting disease rates (Chapter 4, p. 80).",
    "age standardization": "Adjusting rates to a standard population to allow comparison across groups with different age distributions (Chapter 4, p. 94).",
    "age-adjusted mortality rate": "A mortality rate adjusted to a standard population’s age distribution to enable comparisons (Chapter 4, p. 94).",
    "agent": "A factor (e.g., infectious organism, chemical) contributing to disease causation (Chapter 2, p. 35).",
    "age-specific mortality rate": "The mortality rate for a specific age group, often expressed per 100,000 (Chapter 4, p. 80).",
    "age-specific rate": "A rate calculated for a specific age group, used to compare disease occurrence across ages (Chapter 4, p. 80).",
    "allocation concealment": "Ensuring the randomization process in a trial is hidden to prevent bias (Chapter 10, p. 212).",
    "alpha error": "The probability of rejecting the null hypothesis when it is true (Type I error) (Chapter 11, p. 233).",
    "analytic epidemiology": "The study of associations between exposures and outcomes to identify causes (Chapter 1, p. 3).",
    "analytic study": "A study designed to examine associations, often to infer causality, e.g., cohort or case-control studies (Chapter 7, p. 149).",
    "applied epidemiology": "Using epidemiological findings to inform public health practice and policy (Chapter 1, p. 3).",
    "ascertainment bias": "Bias due to differences in how cases or exposures are identified in a study (Chapter 15, p. 303).",
    "association": "A statistical relationship between an exposure and outcome, which may or may not be causal (Chapter 12, p. 254).",
    "asymptomatic infection": "Infection without clinical symptoms, detectable only through testing (Chapter 2, p. 43).",
    "attack rate": "The proportion of an exposed population that develops a disease, often used in outbreak investigations (Chapter 2, p. 35).",
    "attributable fraction": "The proportion of disease in a population attributable to a specific exposure, synonymous with population attributable risk (Chapter 13, p. 281).",
    "attributable fraction (exposed)": "The proportion of disease in the exposed group attributable to the exposure (Chapter 13, p. 275).",
    "attributable risk": "The difference in incidence between exposed and unexposed groups, indicating excess risk due to exposure (Chapter 13, p. 275).",
    "attributable risk fraction": "The proportion of disease in the exposed attributable to the exposure, synonymous with attributable fraction (exposed) (Chapter 13, p. 275).",
    "attributable risk percent": "The percentage of disease incidence in the exposed group attributable to the exposure (Chapter 13, p. 275).",
    "autonomy": "The ethical principle of respecting individuals’ rights to make informed decisions about their participation (Chapter 20, p. 395).",
    "background rate": "The baseline level of disease occurrence in a population without specific exposures (Chapter 12, p. 256).",
    "balancing_sensitivity_specificity": "Optimizing screening tests to balance sensitivity and specificity to minimize false results (Chapter 5, p. 116).",
    "baseline characteristics": "Characteristics of study participants at the start, used to assess group comparability (Chapter 8, p. 179).",
    "baseline risk": "The risk of disease in the absence of a specific exposure, used as a reference (Chapter 12, p. 256).",
    "basic reproductive number (r0)": "The average number of secondary cases produced by one infected individual in a susceptible population (Chapter 2, p. 35).",
    "basic reproductive rate": "Synonymous with basic reproductive number, measuring disease transmissibility (Chapter 2, p. 35).",
    "bayes' theorem": "A mathematical formula to update probabilities based on new evidence, used in diagnostic testing (Chapter 5, p. 121).",
    "Bayesian analysis": "A statistical approach incorporating prior knowledge into probability estimates (Chapter 11, p. 233).",
    "bell-shaped curve": "A normal distribution curve, common in biostatistics for continuous variables (Chapter 11, p. 233).",
    "beneficence": "The ethical principle of acting to benefit participants and minimize harm (Chapter 20, p. 395).",
    "berkson's bias": "Bias in hospital-based case-control studies due to differential admission rates (Chapter 15, p. 303).",
    "beta error": "The probability of failing to reject the null hypothesis when it is false (Type II error) (Chapter 11, p. 233).",
    "bias": "Systematic error in study design, data collection, or analysis leading to incorrect conclusions (Chapter 15, p. 303).",
    "binomial distribution": "A statistical distribution modeling binary outcomes, used in epidemiology (Chapter 11, p. 233).",
    "biological gradient": "A dose-response relationship where increased exposure leads to increased disease risk (Chapter 14, p. 285).",
    "biological marker": "A measurable indicator of a biological state, e.g., blood pressure or genetic marker (Chapter 16, p. 307).",
    "biological plausibility": "The extent to which an association aligns with existing biological knowledge (Chapter 14, p. 269).",
    "biostatistics": "The application of statistical methods to analyze health-related data (Chapter 11, p. 233).",
    "birth cohort": "A group of individuals born during a specific period, followed to study health outcomes (Chapter 8, p. 179).",
    "birth prevalence": "The prevalence of a condition at birth, often used for congenital disorders (Chapter 16, p. 307).",
    "blinding": "Concealing group assignments in a trial to reduce bias, e.g., single- or double-blinding (Chapter 10, p. 212).",
    "blinding (masking)": "Synonymous with blinding, used to minimize bias in experimental studies (Chapter 10, p. 212).",
    "bootstrapping": "A statistical method using repeated sampling to estimate variability of a statistic (Chapter 11, p. 233).",
    "bradford hill criteria": "Criteria (e.g., temporality, strength) for assessing causality in observational studies (Chapter 14, p. 269).",
    "burden of disease": "The overall impact of a disease on a population, including morbidity and mortality (Chapter 3, p. 55).",
    "carrier": "An individual harboring an infectious agent without symptoms, potentially transmitting it (Chapter 2, p. 37).",
    "case ascertainment": "The process of identifying cases for a study or surveillance system (Chapter 3, p. 57).",
    "case definition": "Criteria used to identify individuals with a disease in a study or surveillance (Chapter 2, p. 34).",
    "case report": "A detailed description of a single patient’s disease experience, often hypothesis-generating (Chapter 7, p. 149).",
    "case series": "A descriptive study of multiple individuals with a disease, without a control group (Chapter 7, p. 149).",
    "case": "An individual with the disease or outcome of interest in a study (Chapter 7, p. 155).",
    "case-fatality rate": "The proportion of diagnosed individuals who die from a disease within a period (Chapter 4, p. 87).",
    "case-control study": "A study comparing individuals with a disease (cases) to those without (controls) to identify risk factors (Chapter 7, p. 155).",
    "case-crossover study": "A study where individuals serve as their own controls, comparing exposure at different times (Chapter 7, p. 176).",
    "causal diagram": "A graphical tool to represent causal relationships and identify confounders (Chapter 15, p. 303).",
    "causal inference": "Determining whether an observed association reflects a true cause-effect relationship (Chapter 14, p. 269).",
    "causal pathway": "The sequence of events from exposure to disease outcome (Chapter 14, p. 285).",
    "causality": "The determination that an exposure causes an outcome, based on criteria like temporality (Chapter 14, p. 269).",
    "censoring": "When a subject’s outcome is not observed due to loss to follow-up or study end (Chapter 6, p. 148).",
    "chain of infection": "The sequence of events (agent, reservoir, transmission, host) in infectious disease spread (Chapter 2, p. 35).",
    "chi-square test": "A statistical test to assess differences in proportions or associations (Chapter 11, p. 233).",
    "chronic disease": "A long-term condition, e.g., diabetes, often studied in epidemiology (Chapter 1, p. 19).",
    "clinical disease": "A disease with observable symptoms, as opposed to asymptomatic infection (Chapter 6, p. 137).",
    "clinical significance": "The practical importance of a study’s findings, beyond statistical significance (Chapter 11, p. 233).",
    "clinical trial": "A study testing interventions in a controlled setting, often randomized (Chapter 10, p. 197).",
    "cluster": "A group of disease cases occurring closely in time or place, suggesting a common source (Chapter 2, p. 34).",
    "clustering": "The tendency of cases to occur in close proximity, indicating potential outbreaks (Chapter 2, p. 34).",
    "coherence": "The extent to which an association aligns with existing scientific knowledge (Chapter 14, p. 286).",
    "cohort effect": "Differences in disease rates due to generational or environmental changes (Chapter 8, p. 179).",
    "cohort study": "A study following a group over time to assess disease incidence, comparing exposed and unexposed (Chapter 8, p. 179).",
    "cohort": "A group of individuals followed over time in a study (Chapter 8, p. 179).",
    "common source outbreak": "An outbreak caused by exposure to a single source, e.g., contaminated food (Chapter 2, p. 34).",
    "community trial": "A trial applying interventions to entire communities rather than individuals (Chapter 10, p. 212).",
    "comorbidity adjustment": "Adjusting for multiple diseases in statistical analysis to reduce confounding (Chapter 15, p. 303).",
    "co-morbidity": "The presence of multiple diseases in an individual, complicating outcomes (Chapter 6, p. 137).",
    "competing risk": "An event preventing the primary outcome of interest, e.g., death from another cause (Chapter 6, p. 148).",
    "concordance": "Agreement between observers or tests, often measured by Kappa statistic (Chapter 5, p. 130).",
    "conditional probability": "The probability of an event given another event has occurred (Chapter 12, p. 261).",
    "confidence interval": "A range within which the true population parameter is likely to lie, typically 95% (Chapter 11, p. 233).",
    "confidence level": "The probability that a confidence interval contains the true parameter value, typically 95% (Chapter 11, p. 233).",
    "confounding by indication": "Bias where treatment is influenced by the indication, affecting observational studies (Chapter 15, p. 303).",
    "confounding": "Distortion of an exposure-outcome association due to a third variable (Chapter 15, p. 303).",
    "consistency": "The replication of an association across different studies or populations (Chapter 14, p. 286).",
    "contact tracing": "Identifying and monitoring individuals exposed to an infectious disease to prevent spread (Chapter 2, p. 37).",
    "contagious disease": "A disease spread through direct or indirect contact (Chapter 2, p. 43).",
    "contagious": "Capable of being transmitted from one individual to another (Chapter 2, p. 43).",
    "continuous variable": "A variable with a range of values, e.g., blood pressure (Chapter 11, p. 233).",
    "control group": "The group in a study not receiving the intervention or exposure, used for comparison (Chapter 10, p. 198).",
    "control selection": "Choosing appropriate controls in a case-control study to minimize bias (Chapter 7, p. 169).",
    "correlation": "A statistical measure of the relationship between two variables, not implying causation (Chapter 12, p. 254).",
    "cost-effectiveness analysis": "Evaluating costs and health outcomes of interventions to guide resource allocation (Chapter 18, p. 374).",
    "cox proportional hazards regression": "A statistical model for time-to-event data, assuming constant hazard ratios (Chapter 6, p. 148).",
    "cross-over design": "A trial design where participants receive multiple treatments in sequence (Chapter 10, p. 223).",
    "crossover trial": "Synonymous with cross-over design, testing multiple interventions sequentially (Chapter 10, p. 223).",
    "cross-sectional study": "A study examining exposure and outcome at a single point in time (Chapter 7, p. 149).",
    "crude mortality rate": "The total number of deaths divided by the population, without adjustment (Chapter 4, p. 106).",
    "crude rate": "A rate calculated without adjustment for confounding factors (Chapter 4, p. 106).",
    "cumulative incidence": "The proportion of a population at risk developing a disease over a period (Chapter 3, p. 44).",
    "cumulative incidence rate": "The number of new cases divided by the population at risk over a period (Chapter 3, p. 44).",
    "cumulative incidence ratio": "The ratio of cumulative incidence in exposed versus unexposed groups (Chapter 13, p. 424).",
    "cumulative risk": "The total risk of an event over a specified period (Chapter 12, p. 254).",
    "dalys (disability-adjusted life years)": "A measure of disease burden combining years of life lost and years lived with disability (Chapter 4, p. 87).",
    "data cleaning": "The process of correcting or removing errors in data to ensure accuracy (Chapter 7, p. 155).",
    "data collection": "Gathering information on exposures and outcomes for a study (Chapter 7, p. 155).",
    "data dredging": "Searching data for associations without a hypothesis, increasing false positives (Chapter 15, p. 303).",
    "data quality": "The accuracy, completeness, and reliability of data used in studies (Chapter 7, p. 155).",
    "dependent variable": "The outcome variable in a study, influenced by independent variables (Chapter 12, p. 256).",
    "descriptive epidemiology": "Studying disease distribution by person, place, and time (Chapter 1, p. 3).",
    "determinant": "A factor influencing health outcomes, e.g., biological or environmental (Chapter 1, p. 3).",
    "determinants": "Multiple factors contributing to disease occurrence (Chapter 1, p. 3).",
    "diagnostic accuracy": "The ability of a test to correctly identify diseased and non-diseased individuals (Chapter 5, p. 94).",
    "diagnostic test": "A test to detect or confirm a disease, evaluated by sensitivity and specificity (Chapter 5, p. 116).",
    "differential misclassification": "Misclassification varying between study groups, leading to bias (Chapter 15, p. 303).",
    "direct standardization": "Adjusting rates using a standard population’s age-specific rates (Chapter 4, p. 94).",
    "direct transmission": "Disease spread through direct contact or droplet spread (Chapter 2, p. 43).",
    "discrete variable": "A variable with distinct values, e.g., number of cases (Chapter 11, p. 233).",
    "disease burden": "The overall impact of a disease, including morbidity and mortality (Chapter 3, p. 55).",
    "disease cluster": "An aggregation of cases in a specific area or time, suggesting a common source (Chapter 2, p. 34).",
    "disease determinants": "Factors contributing to disease occurrence, e.g., genetic or environmental (Chapter 1, p. 3).",
    "disease distribution": "The pattern of disease occurrence by person, place, and time (Chapter 1, p. 3).",
    "disease frequency": "The occurrence of disease, measured by incidence or prevalence (Chapter 3, p. 55).",
    "disease mapping": "Plotting disease occurrence geographically to identify patterns (Chapter 3, p. 68).",
    "disease progression": "The advancement of a disease through stages, from onset to outcome (Chapter 6, p. 137).",
    "disease reservoir": "The population or environment where an infectious agent resides (Chapter 2, p. 37).",
    "disease spectrum": "The range of disease manifestations, from mild to severe (Chapter 6, p. 137).",
    "disease surveillance": "Ongoing collection and analysis of health data to monitor disease (Chapter 3, p. 57).",
    "disease_control": "Implementing measures like vaccination or quarantine to reduce disease spread (Chapter 2, p. 37).",
    "disease_transmission_dynamics": "The study of how diseases spread via infectious agents or environmental factors (Chapter 2, p. 21–39).",
    "dose-response relationship": "An association where increased exposure leads to increased disease risk (Chapter 14, p. 285).",
    "double-blind trial": "A trial where neither participants nor researchers know group assignments (Chapter 10, p. 212).",
    "double-blinding": "Synonymous with double-blind trial, reducing bias in trials (Chapter 10, p. 212).",
    "ecologic fallacy": "Incorrectly inferring individual-level associations from group-level data (Chapter 7, p. 149).",
    "ecologic study": "A study examining associations at the group level, not individual level (Chapter 7, p. 149).",
    "ecological fallacy": "Synonymous with ecologic fallacy, misinterpreting group-level data (Chapter 7, p. 149).",
    "ecological study": "Synonymous with ecologic study, analyzing group-level associations (Chapter 7, p. 149).",
    "effect estimate": "A statistical measure of association strength, e.g., odds ratio or relative risk (Chapter 12, p. 256).",
    "effect modification": "When the effect of an exposure on an outcome varies by a third variable (Chapter 15, p. 315).",
    "effect size": "The magnitude of an association between exposure and outcome (Chapter 12, p. 256).",
    "effectiveness": "The ability of an intervention to produce effects in real-world settings (Chapter 10, p. 213).",
    "efficacy": "The ability of an intervention to produce effects under ideal conditions (Chapter 10, p. 213).",
    "efficiency": "Achieving maximum health benefits with minimal resources in interventions (Chapter 18, p. 374).",
    "endemic": "The habitual presence of a disease at a baseline level in a population (Chapter 2, p. 23).",
    "endogenous factor": "An internal factor, e.g., genetics, influencing disease risk (Chapter 16, p. 307).",
    "environment": "External factors (e.g., air, water) affecting disease occurrence (Chapter 2, p. 35).",
    "environmental epidemiology": "The study of environmental factors and their impact on health (Chapter 16, p. 307).",
    "environmental exposure": "Contact with environmental factors that may influence disease (Chapter 2, p. 35).",
    "epidemic": "A sudden increase in disease cases above the endemic level (Chapter 2, p. 24).",
    "epidemic curve": "A graph showing the number of cases over time in an outbreak (Chapter 2, p. 35).",
    "epidemiologic transition": "The shift from infectious to chronic diseases as populations develop (Chapter 1, p. 19).",
    "epidemiology": "The study of disease distribution and determinants in populations to control health problems (Chapter 1, p. 3).",
    "ethical_conduct": "Adhering to ethical standards like informed consent in research (Chapter 20, p. 395).",
    "ethical_considerations": "Ensuring informed consent, privacy, and fairness in epidemiological studies (Chapter 20, p. 395).",
    "etiologic": "Related to the cause of a disease (Chapter 1, p. 3).",
    "etiology": "The study of disease causes (Chapter 1, p. 3).",
    "evidence_based_decisions": "Basing health policies on robust epidemiological data (Chapter 19, p. 377).",
    "evidence-based public health": "Applying epidemiological evidence to public health practice (Chapter 19, p. 377).",
    "excess risk": "The additional risk of disease due to an exposure, synonymous with attributable risk (Chapter 13, p. 275).",
    "exogenous factor": "An external factor, e.g., environmental exposure, influencing disease (Chapter 16, p. 307).",
    "experimental study": "A study where investigators assign exposures, e.g., randomized trials (Chapter 10, p. 197).",
    "exposure": "Contact with a factor hypothesized to influence disease risk (Chapter 7, p. 155).",
    "exposure assessment": "Measuring the level or intensity of exposure to a risk factor (Chapter 7, p. 155).",
    "exposure prevalence": "The proportion of a population exposed to a specific risk factor (Chapter 12, p. 270).",
    "external validity": "The extent to which study findings apply to other populations (Chapter 5, p. 94).",
    "external validity (generalizability)": "Synonymous with external validity, assessing generalizability (Chapter 5, p. 94).",
    "factorial design": "A trial testing multiple interventions simultaneously to assess interactions (Chapter 10, p. 225).",
    "false negative": "A test result incorrectly indicating the absence of a condition (Chapter 5, p. 116).",
    "false positive": "A test result incorrectly indicating the presence of a condition (Chapter 5, p. 116).",
    "feasibility study": "A preliminary study to assess the practicality of a larger study (Chapter 7, p. 149).",
    "field trial": "A trial conducted in real-world settings to test interventions (Chapter 10, p. 212).",
    "fixed cohort": "A cohort where all participants are enrolled at the same time (Chapter 8, p. 179).",
    "follow-up bias": "Bias due to differential loss to follow-up between study groups (Chapter 8, p. 179).",
    "follow-up period": "The time during which participants are observed for outcomes (Chapter 8, p. 179).",
    "fomite": "An inanimate object carrying infectious agents, aiding transmission (Chapter 2, p. 43).",
    "frequency distribution": "A table or graph showing the distribution of a variable’s values (Chapter 11, p. 233).",
    "generalizability": "The ability to apply study findings to other populations (Chapter 5, p. 94).",
    "generalizability_principle": "Study findings should be applicable to broader populations for impact (Chapter 15, p. 303).",
    "generation time": "The time between infection in one individual and transmission to another (Chapter 2, p. 35).",
    "genetic epidemiology": "Studying genetic and environmental interactions in disease causation (Chapter 16, p. 307).",
    "genetic_environmental_interactions": "The interplay of genetic and environmental factors in disease risk (Chapter 16, p. 307).",
    "gold standard": "The best available test or method for diagnosing a condition (Chapter 5, p. 116).",
    "hazard function": "The instantaneous risk of an event at a given time (Chapter 6, p. 148).",
    "hazard ratio": "The ratio of event rates in two groups over time, used in survival analysis (Chapter 6, p. 148).",
    "health disparities": "Differences in health outcomes across population groups due to social or economic factors (Chapter 19, p. 392).",
    "healthy volunteer bias": "Bias where healthier individuals are more likely to participate in studies (Chapter 15, p. 303).",
    "healthy worker effect": "Bias where workers appear healthier than the general population (Chapter 8, p. 179).",
    "herd immunity": "Population resistance to a disease due to a high proportion of immune individuals (Chapter 2, p. 35).",
    "historical_examples": "Cases like John Snow’s cholera study illustrating epidemiological methods (Chapter 1, p. 15, 29).",
    "host": "The organism (e.g., human) affected by a disease agent (Chapter 2, p. 35).",
    "hypothesis": "A proposed explanation for an observed phenomenon, tested in studies (Chapter 11, p. 233).",
    "hypothesis testing": "Statistical methods to test the validity of a hypothesis (Chapter 11, p. 233).",
    "iatrogenic disease": "A disease caused by medical intervention or treatment (Chapter 6, p. 137).",
    "immunity": "Resistance to a specific disease, either natural or acquired (Chapter 2, p. 35).",
    "incidence": "The number of new disease cases in a population over a period (Chapter 3, p. 44).",
    "incidence density": "The rate of new cases per unit of person-time at risk (Chapter 3, p. 44).",
    "incidence proportion": "The proportion of a population developing a disease over a period (Chapter 3, p. 44).",
    "incidence rate": "The number of new cases per unit of person-time at risk (Chapter 3, p. 44).",
    "incidence rate ratio": "The ratio of incidence rates in exposed versus unexposed groups (Chapter 12, p. 256).",
    "incubation period": "The time between exposure to an infectious agent and symptom onset (Chapter 2, p. 43).",
    "independent variable": "The exposure or factor hypothesized to influence the outcome (Chapter 12, p. 256).",
    "index case": "The first identified case in an outbreak, often the source of spread (Chapter 2, p. 34).",
    "indirect standardization": "Adjusting rates using a standard population’s age-specific rates (Chapter 4, p. 94).",
    "indirect transmission": "Disease spread through vehicles like air, water, or vectors (Chapter 2, p. 43).",
    "individual-level data": "Data collected on individual participants, as opposed to group-level data (Chapter 7, p. 149).",
    "induction period": "The time between exposure and disease initiation (Chapter 6, p. 137).",
    "infectious agent": "A microorganism causing disease, e.g., bacteria or virus (Chapter 2, p. 35).",
    "infectious disease epidemiology": "Studying the spread and control of infectious diseases (Chapter 2, p. 21–39).",
    "infectivity": "The ability of an agent to infect a host (Chapter 2, p. 35).",
    "information bias": "Bias due to errors in measuring exposure or outcome data (Chapter 15, p. 303).",
    "informed consent": "Ensuring participants understand a study’s purpose and risks before agreeing (Chapter 20, p. 395).",
    "institutional review board (irb)": "A committee reviewing research to ensure ethical standards (Chapter 20, p. 395).",
    "instrumental variable": "A variable controlling for unmeasured confounding in observational studies (Chapter 15, p. 303).",
    "intention-to-treat analysis": "Analyzing trial participants based on initial group assignment, regardless of adherence (Chapter 10, p. 213).",
    "interaction": "When the effect of one exposure on an outcome depends on another factor (Chapter 15, p. 315).",
    "interaction effect": "The combined effect of exposures beyond their individual effects (Chapter 15, p. 315).",
    "interaction term": "A statistical term modeling effect modification in regression (Chapter 15, p. 315).",
    "internal validity": "The extent to which a study’s results are free from bias and confounding (Chapter 5, p. 94).",
    "interobserver reliability": "Consistency of measurements between different observers (Chapter 5, p. 130).",
    "interval variable": "A variable with equal intervals between values, e.g., temperature (Chapter 11, p. 233).",
    "interviewer bias": "Bias introduced by the interviewer’s influence on responses (Chapter 15, p. 303).",
    "intraobserver reliability": "Consistency of measurements by the same observer over time (Chapter 5, p. 130).",
    "isolation": "Separating infected individuals to prevent disease spread (Chapter 2, p. 37).",
    "justice": "The ethical principle of ensuring fairness in research participant selection (Chapter 20, p. 395).",
    "kaplan-meier curve": "A graph showing survival probabilities over time, accounting for censoring (Chapter 6, p. 148).",
    "Kaplan-Meier estimator": "A method to estimate survival probabilities, accounting for censoring (Chapter 6, p. 148).",
    "Kappa statistic": "A measure of agreement between observers beyond chance (Chapter 5, p. 130).",
    "latency period": "The time between exposure and disease detection (Chapter 6, p. 137).",
    "latent period": "Synonymous with latency period, time from exposure to disease onset (Chapter 6, p. 137).",
    "lead time bias": "Apparent survival increase due to early detection without true benefit (Chapter 18, p. 374).",
    "lead-time bias": "Synonymous with lead time bias, affecting screening evaluations (Chapter 18, p. 374).",
    "length time bias": "Bias where screening detects slower-progressing diseases, inflating benefits (Chapter 18, p. 374).",
    "levels of prevention": "Primary, secondary, and tertiary prevention to reduce disease impact (Chapter 1, p. 3).",
    "life course epidemiology": "Studying health across the lifespan, considering cumulative exposures (Chapter 16, p. 307).",
    "life expectancy": "The average time an individual is expected to live, based on mortality rates (Chapter 4, p. 87).",
    "life table": "A method to estimate survival probabilities over time in a cohort (Chapter 6, p. 148).",
    "likelihood ratio": "The ratio of a test result’s probability in diseased versus non-diseased individuals (Chapter 5, p. 121).",
    "likelihood ratio negative": "The ratio of (1 - sensitivity) to specificity, indicating diagnostic strength (Chapter 5, p. 121).",
    "likelihood ratio positive": "The ratio of sensitivity to (1 - specificity), indicating diagnostic strength (Chapter 5, p. 121).",
    "linear regression": "A statistical method modeling the relationship between a continuous outcome and predictors (Chapter 12, p. 256).",
    "logistic regression": "A method modeling binary outcomes with exposures (Chapter 12, p. 256).",
    "longitudinal study": "A study following participants over time to observe outcomes (Chapter 8, p. 179).",
    "loss to follow-up": "When participants drop out of a study, potentially biasing results (Chapter 8, p. 179).",
    "loss to follow-up bias": "Bias due to differential dropout rates between study groups (Chapter 8, p. 179).",
    "matching": "Selecting controls with similar characteristics to cases to reduce confounding (Chapter 7, p. 169).",
    "matching ratio": "The ratio of controls to cases in a case-control study, e.g., 1:1 (Chapter 7, p. 169).",
    "maternal mortality rate": "The number of maternal deaths per 100,000 live births (Chapter 4, p. 80).",
    "mean": "The average value of a dataset, a measure of central tendency (Chapter 11, p. 233).",
    "measurement error": "Errors in collecting or recording data, reducing accuracy (Chapter 5, p. 131).",
    "measures of association": "Statistics like relative risk or odds ratio quantifying exposure-outcome relationships (Chapter 12, p. 255).",
    "measures of central tendency": "Statistics like mean, median, and mode summarizing data (Chapter 11, p. 233).",
    "measures of disease frequency": "Incidence and prevalence, quantifying disease occurrence (Chapter 3, p. 55).",
    "measures of dispersion": "Statistics like range and standard deviation measuring data variability (Chapter 11, p. 233).",
    "measures of impact": "Metrics like attributable risk measuring exposure effects (Chapter 13, p. 275).",
    "median": "The middle value in a dataset, a measure of central tendency (Chapter 11, p. 233).",
    "meta-analysis": "Combining results from multiple studies to estimate overall effects (Chapter 11, p. 242).",
    "migration bias": "Bias due to participants moving in or out of a study area (Chapter 8, p. 179).",
    "misclassification": "Incorrect assignment of exposure or disease status, leading to bias (Chapter 15, p. 303).",
    "misclassification bias": "Bias due to errors in classifying exposure or outcome (Chapter 15, p. 303).",
    "mixed outbreak": "An outbreak combining common source and propagated transmission (Chapter 2, p. 34).",
    "mode": "The most frequent value in a dataset, a measure of central tendency (Chapter 11, p. 233).",
    "morbidity": "The incidence or prevalence of disease in a population (Chapter 3, p. 55).",
    "morbidity rate": "The rate of disease occurrence, expressed as incidence or prevalence (Chapter 3, p. 55).",
    "mortality": "The occurrence of death in a population (Chapter 4, p. 80).",
    "mortality rate": "The number of deaths in a population over a time, often per 100,000 (Chapter 4, p. 80).",
    "multiplicative model": "A model assuming combined effects of exposures are the product of individual effects (Chapter 15, p. 315).",
    "multivariable analysis": "Adjusting for multiple confounders simultaneously in statistical models (Chapter 15, p. 303).",
    "multivariable regression": "Regression models adjusting for multiple variables (Chapter 12, p. 256).",
    "natural experiment": "A study exploiting naturally occurring exposure variations (Chapter 7, p. 149).",
    "natural history of disease": "The progression of a disease from onset to outcome without intervention (Chapter 6, p. 137).",
    "negative predictive value": "The proportion of negative test results that are true negatives (Chapter 5, p. 121).",
    "neonatal mortality rate": "The number of deaths within 28 days of birth per 1,000 live births (Chapter 4, p. 80).",
    "nested case-control study": "A case-control study within a cohort, using cohort members as controls (Chapter 8, p. 189).",
    "nominal variable": "A variable with categories without order, e.g., gender (Chapter 11, p. 233).",
    "non-differential misclassification": "Misclassification not varying between study groups (Chapter 15, p. 303).",
    "non-maleficence": "The ethical principle of avoiding harm to participants (Chapter 20, p. 395).",
    "non-response bias": "Bias due to differences between responders and non-responders (Chapter 15, p. 303).",
    "notifiable disease": "A disease required to be reported to public health authorities (Chapter 3, p. 76).",
    "null hypothesis": "The assumption of no association between exposure and outcome (Chapter 11, p. 233).",
    "number needed to harm (nnh)": "The number of individuals exposed to an intervention to cause one adverse outcome (Chapter 10, p. 213).",
    "number needed to treat": "The number of individuals treated to prevent one adverse outcome (Chapter 10, p. 213).",
    "observational data": "Data collected without experimental manipulation (Chapter 7, p. 149).",
    "observational study": "A study where exposures are not assigned, e.g., cohort or case-control (Chapter 7, p. 149).",
    "observational study design": "Designs like cohort or case-control where exposures are observed, not assigned (Chapter 7, p. 149).",
    "odds": "The ratio of the probability of an event occurring to not occurring (Chapter 12, p. 261).",
    "odds ratio": "The ratio of exposure odds in cases to controls, used in case-control studies (Chapter 12, p. 261).",
    "odds ratio approximation": "The odds ratio approximates relative risk when the disease is rare (Chapter 12, p. 261).",
    "one-sided test": "A statistical test with a hypothesis in one direction only (Chapter 11, p. 233).",
    "ordinal variable": "A variable with ordered categories, e.g., disease severity (Chapter 11, p. 233).",
    "outbreak": "A localized epidemic, often sudden increases in disease cases (Chapter 2, p. 34).",
    "overdiagnosis bias": "Bias where screening detects non-progressive conditions, inflating benefits (Chapter 18, p. 374).",
    "overmatching": "Excessive matching in case-control studies, reducing ability to detect associations (Chapter 7, p. 169).",
    "pandemic": "An epidemic affecting a large geographic area or population (Chapter 2, p. 24).",
    "parsimony": "Favoring simpler, biologically plausible explanations for associations (Chapter 14, p. 286).",
    "passive immunity": "Temporary immunity from external sources, e.g., maternal antibodies (Chapter 2, p. 35).",
    "passive surveillance": "A surveillance system relying on reports from providers, not active case-finding (Chapter 3, p. 57).",
    "pathogenesis": "The biological process by which a disease develops (Chapter 6, p. 137).",
    "pathogenicity": "The ability of an agent to cause disease in an infected host (Chapter 2, p. 35).",
    "period prevalence": "The proportion of a population with a disease over a specified period (Chapter 3, p. 52).",
    "per-protocol analysis": "Analyzing trial participants based on adherence to the protocol (Chapter 10, p. 213).",
    "person-time": "The sum of time each individual is at risk, used for incidence rates (Chapter 3, p. 44).",
    "person-years": "A measure of person-time for calculating incidence rates (Chapter 3, p. 44).",
    "pilot study": "A small-scale study to test feasibility or methods before a larger study (Chapter 7, p. 149).",
    "placebo": "An inactive substance or treatment used as a control in trials (Chapter 10, p. 212).",
    "placebo effect": "Improvement due to belief in receiving treatment, not the treatment itself (Chapter 10, p. 212).",
    "point prevalence": "The proportion of a population with a disease at a single point in time (Chapter 3, p. 52).",
    "point source outbreak": "An outbreak from exposure to a single source at one time (Chapter 2, p. 34).",
    "poisson regression": "A statistical model for count or rate data, used in epidemiology (Chapter 12, p. 256).",
    "population": "The group of individuals studied in epidemiology (Chapter 1, p. 3).",
    "population at risk": "Individuals susceptible to developing a specific disease (Chapter 3, p. 44).",
    "population attributable fraction (paf)": "The proportion of disease incidence attributable to an exposure (Chapter 13, p. 281).",
    "population attributable risk": "The proportion of disease incidence in a population due to an exposure (Chapter 13, p. 281).",
    "population pyramid": "A graph of a population’s age and sex distribution (Chapter 4, p. 80).",
    "portal of entry": "The route through which an infectious agent enters a host (Chapter 2, p. 35).",
    "portal of exit": "The route through which an infectious agent leaves a host (Chapter 2, p. 35).",
    "positive predictive value": "The proportion of positive test results that are true positives (Chapter 5, p. 121).",
    "post-neonatal mortality rate": "The number of deaths from 28 days to 1 year per 1,000 live births (Chapter 4, p. 80).",
    "power": "The probability of detecting a true effect, dependent on sample size (Chapter 11, p. 234).",
    "precision": "The consistency of repeated measurements, related to random error (Chapter 5, p. 131).",
    "precision medicine": "Tailoring interventions based on individual genetic or environmental profiles (Chapter 16, p. 307).",
    "preclinical phase": "The stage of disease before symptoms, detectable by screening (Chapter 6, p. 137).",
    "prevalence": "The proportion of a population with a disease at a given time (Chapter 3, p. 52).",
    "prevalence odds ratio": "The odds of disease in exposed versus unexposed, used in cross-sectional studies (Chapter 12, p. 261).",
    "prevalence pool": "The total number of existing disease cases in a population (Chapter 3, p. 52).",
    "prevalence rate": "The proportion of a population with a disease, often as a percentage (Chapter 3, p. 52).",
    "preventive fraction": "The proportion of potential cases prevented by an exposure or intervention (Chapter 13, p. 275).",
    "primary case": "The first case in an outbreak, often the source of spread (Chapter 2, p. 34).",
    "primary data": "Data collected directly by researchers for a study (Chapter 7, p. 155).",
    "primary infection": "The initial infection by a pathogen in a host (Chapter 2, p. 35).",
    "primary prevention": "Interventions to prevent disease occurrence, e.g., vaccination (Chapter 1, p. 3).",
    "propagated outbreak": "An outbreak where disease spreads from person to person (Chapter 2, p. 34).",
    "propensity score": "A score estimating the probability of exposure, used to adjust for confounding (Chapter 15, p. 303).",
    "proportion": "A ratio where the numerator is part of the denominator, e.g., prevalence (Chapter 3, p. 52).",
    "proportional hazards model": "A model assuming constant hazard ratios over time (Chapter 6, p. 148).",
    "proportionate mortality": "The proportion of deaths attributed to a specific cause (Chapter 4, p. 84).",
    "prospective cohort study": "A cohort study following participants forward in time (Chapter 8, p. 179).",
    "prospective study": "A study collecting data forward in time, e.g., cohort studies (Chapter 8, p. 179).",
    "proxy variable": "A variable used as a substitute for an unmeasured exposure or outcome (Chapter 15, p. 303).",
    "public health intervention": "Actions to improve population health, e.g., vaccination campaigns (Chapter 1, p. 3).",
    "public_health_impact": "The effect of epidemiological research on public health practice (Chapter 1, p. 3).",
    "public_policy_implications": "How epidemiological findings shape health policies (Chapter 19, p. 377).",
    "publication bias": "Bias where significant results are more likely to be published (Chapter 15, p. 303).",
    "p-value": "The probability of observing results as extreme, assuming the null hypothesis (Chapter 11, p. 233).",
    "qalys (quality-adjusted life years)": "A measure of disease burden incorporating quality and quantity of life (Chapter 4, p. 87).",
    "quarantine": "Restricting movement of exposed individuals to prevent disease spread (Chapter 2, p. 37).",
    "quasi-experimental study": "A study with intervention but without randomization (Chapter 10, p. 197).",
    "random error": "Variability in results due to chance, reducible by larger samples (Chapter 15, p. 303).",
    "random sampling": "Selecting participants randomly to ensure representativeness (Chapter 7, p. 149).",
    "randomization": "Assigning participants to groups by chance to reduce bias (Chapter 10, p. 198).",
    "randomized controlled trial": "An experimental study with random assignment to test interventions (Chapter 10, p. 198).",
    "range": "The difference between the highest and lowest values in a dataset (Chapter 11, p. 233).",
    "rate": "A measure of event occurrence per unit of time or population (Chapter 3, p. 44).",
    "rate ratio": "The ratio of two rates, similar to relative risk (Chapter 12, p. 256).",
    "ratio": "A comparison of two quantities, e.g., odds ratio (Chapter 12, p. 261).",
    "ratio variable": "A variable with a true zero and equal intervals, e.g., weight (Chapter 11, p. 233).",
    "recall bias": "Bias when cases and controls differ in recalling past exposures (Chapter 7, p. 175).",
    "recall period": "The time frame for which participants recall exposures (Chapter 7, p. 175).",
    "registry": "A database collecting standardized data on diseases, e.g., cancer registry (Chapter 3, p. 76).",
    "regression analysis": "Statistical methods to model relationships between variables (Chapter 12, p. 256).",
    "relative risk": "The ratio of disease incidence in exposed versus unexposed groups (Chapter 12, p. 256).",
    "relative risk reduction": "The proportion by which an intervention reduces risk (Chapter 10, p. 213).",
    "relative survival": "The survival rate of a diseased population compared to a standard population (Chapter 6, p. 156).",
    "reliability": "The consistency of a measurement when repeated (Chapter 5, p. 131).",
    "reliability (reproducibility)": "Synonymous with reliability, measuring consistency (Chapter 5, p. 131).",
    "reporting bias": "Bias due to selective reporting of study outcomes (Chapter 15, p. 303).",
    "representativeness": "The extent to which a sample reflects the target population (Chapter 7, p. 149).",
    "reproducibility": "The ability to replicate study results in different settings (Chapter 14, p. 286).",
    "reservoir": "The population or environment where an infectious agent resides (Chapter 2, p. 37).",
    "residual confounding": "Confounding remaining after adjustment for known confounders (Chapter 15, p. 303).",
    "resistance": "The ability of a host to resist infection or disease (Chapter 2, p. 35).",
    "restriction": "Limiting study participants to reduce confounding, e.g., studying only one age group (Chapter 15, p. 303).",
    "retrospective cohort study": "A cohort study using historical data (Chapter 8, p. 188).",
    "retrospective study": "A study using past data to examine exposures and outcomes (Chapter 7, p. 155).",
    "reverse causality": "When the outcome influences the exposure, complicating causal inference (Chapter 14, p. 285).",
    "risk": "The probability of developing a disease over a period (Chapter 12, p. 254).",
    "risk assessment": "Evaluating the probability and impact of health outcomes (Chapter 12, p. 254).",
    "risk communication": "Conveying epidemiological findings to inform decisions (Chapter 19, p. 393).",
    "risk difference": "The difference in risk between exposed and unexposed groups (Chapter 13, p. 275).",
    "risk factor": "A characteristic associated with increased disease probability (Chapter 7, p. 155).",
    "risk ratio": "Synonymous with relative risk, comparing disease risk in exposed versus unexposed (Chapter 12, p. 256).",
    "sample": "A subset of a population selected for study (Chapter 7, p. 149).",
    "sample size": "The number of participants in a study, affecting power and precision (Chapter 11, p. 234).",
    "sampling": "The process of selecting participants for a study (Chapter 7, p. 149).",
    "sampling error": "Variability in results due to studying a sample, not the entire population (Chapter 15, p. 303).",
    "scientific_rigor": "Minimizing bias and confounding through robust study design (Chapter 15, p. 303).",
    "screening": "Testing asymptomatic individuals to detect disease early (Chapter 18, p. 353).",
    "screening program": "Systematic efforts to detect disease early in populations (Chapter 18, p. 353).",
    "screening test": "A test to detect disease in asymptomatic individuals (Chapter 18, p. 353).",
    "screening_evaluation": "Assessing screening programs for effectiveness and ethics (Chapter 18, p. 353–389).",
    "secondary attack rate": "The proportion of exposed contacts developing a disease after exposure to a primary case (Chapter 2, p. 35).",
    "secondary data": "Data collected by others, used in studies (Chapter 7, p. 155).",
    "secondary prevention": "Early detection and treatment to prevent disease progression (Chapter 18, p. 353).",
    "secular trend": "Long-term changes in disease rates over time (Chapter 3, p. 55).",
    "selection bias": "Bias from non-representative participant selection (Chapter 15, p. 303).",
    "selection criteria": "Rules for including or excluding study participants (Chapter 7, p. 155).",
    "sensitivity": "The proportion of true positive cases correctly identified by a test (Chapter 5, p. 116).",
    "sensitivity analysis": "Testing how changes in assumptions affect study results (Chapter 15, p. 303).",
    "sentinel surveillance": "Monitoring specific populations or sites to detect disease trends (Chapter 3, p. 57).",
    "serial interval": "The time between symptom onset in a primary case and a secondary case (Chapter 2, p. 35).",
    "severity (virulence)": "The degree of harm caused by a disease (Chapter 2, p. 35).",
    "single-blind trial": "A trial where only participants are unaware of group assignments (Chapter 10, p. 212).",
    "single-blinding": "Synonymous with single-blind trial, reducing participant bias (Chapter 10, p. 212).",
    "social determinants of health": "Social and economic factors influencing health outcomes (Chapter 19, p. 392).",
    "social epidemiology": "Studying social determinants and their impact on health (Chapter 19, p. 392).",
    "specific rate": "A rate for a specific subgroup, e.g., sex-specific rate (Chapter 4, p. 80).",
    "specificity": "The proportion of true negative cases correctly identified by a test (Chapter 5, p. 116).",
    "specificity analysis": "Evaluating a test’s ability to identify those without the disease (Chapter 5, p. 116).",
    "sporadic": "Occasional, isolated disease cases without a clear pattern (Chapter 2, p. 23).",
    "standard deviation": "A measure of data variability around the mean (Chapter 11, p. 233).",
    "standard error": "A measure of the variability of a sample statistic (Chapter 11, p. 233).",
    "standard population": "A reference population used to adjust rates for comparison (Chapter 4, p. 94).",
    "standardized incidence ratio": "The ratio of observed to expected disease cases (Chapter 3, p. 44).",
    "standardized mortality ratio": "The ratio of observed to expected deaths in a population (Chapter 4, p. 94).",
    "statistical power": "The ability to detect a true effect, dependent on sample size (Chapter 11, p. 234).",
    "statistical significance": "The likelihood that results are not due to chance, often p < 0.05 (Chapter 11, p. 233).",
    "stratification": "Dividing data into subgroups to control for confounding (Chapter 15, p. 303).",
    "stratified analysis": "Analyzing data within subgroups to reduce confounding (Chapter 15, p. 303).",
    "strength of association": "The magnitude of an exposure-outcome relationship, e.g., high relative risk (Chapter 14, p. 269).",
    "study base": "The population from which cases and controls are drawn (Chapter 7, p. 155).",
    "study population": "The group of individuals included in a study (Chapter 7, p. 155).",
    "study_designs": "Observational and experimental designs used in epidemiology (Chapters 7–9, p. 149–207).",
    "sufficient-component cause model": "A model where multiple factors combine to cause disease (Chapter 14, p. 285).",
    "surveillance": "Ongoing monitoring of disease to detect trends or outbreaks (Chapter 3, p. 57).",
    "surveillance system": "A system for collecting and analyzing health data (Chapter 3, p. 57).",
    "surveillance systems": "Multiple systems for monitoring disease trends (Chapter 3, p. 57).",
    "survival analysis": "Statistical methods for time-to-event data, e.g., time to death (Chapter 6, p. 148).",
    "survival curve": "A graph showing the proportion surviving over time (Chapter 6, p. 148).",
    "survival probability": "The probability of surviving past a specific time (Chapter 6, p. 148).",
    "susceptible host": "An individual at risk of infection due to lack of immunity (Chapter 2, p. 35).",
    "syndromic surveillance": "Monitoring symptoms to detect disease outbreaks early (Chapter 3, p. 57).",
    "systematic error": "Error due to study design or measurement flaws, leading to bias (Chapter 15, p. 303).",
    "systematic review": "A structured review of studies to summarize evidence (Chapter 11, p. 242).",
    "temporal relationship": "The requirement that exposure precedes the outcome for causality (Chapter 14, p. 269).",
    "temporal trend": "Changes in disease rates over time, analyzed descriptively (Chapter 3, p. 55).",
    "temporal_sequence": "Synonymous with temporal relationship, exposure precedes outcome (Chapter 14, p. 269).",
    "temporality": "The principle that cause must precede effect in causal inference (Chapter 14, p. 269).",
    "tertiary prevention": "Interventions to reduce complications of established disease (Chapter 1, p. 3).",
    "test-retest reliability": "Consistency of a test when repeated under the same conditions (Chapter 5, p. 131).",
    "time-dependent exposure": "An exposure varying over time, requiring special analysis (Chapter 8, p. 179).",
    "time-to-event data": "Data measuring time until an event occurs, used in survival analysis (Chapter 6, p. 148).",
    "transmissibility": "The ease with which a disease spreads between hosts (Chapter 2, p. 35).",
    "triad of causation": "The interaction of agent, host, and environment in disease causation (Chapter 2, p. 35).",
    "true negative": "A test result correctly identifying an individual without the disease (Chapter 5, p. 116).",
    "true positive": "A test result correctly identifying an individual with the disease (Chapter 5, p. 116).",
    "true rate": "The actual rate of disease in a population, often estimated (Chapter 3, p. 44).",
    "t-test": "A statistical test comparing means between two groups (Chapter 11, p. 233).",
    "two-sided test": "A statistical test with a hypothesis in both directions (Chapter 11, p. 233).",
    "type I error": "Rejecting the null hypothesis when it is true (Chapter 11, p. 233).",
    "type II error": "Failing to reject the null hypothesis when it is false (Chapter 11, p. 233).",
    "unbiased estimate": "An estimate free from systematic error, reflecting the true value (Chapter 11, p. 233).",
    "under-reporting": "Failure to report all cases of a disease, affecting surveillance (Chapter 3, p. 76).",
    "unmatched case-control study": "A case-control study without matching controls to cases (Chapter 7, p. 169).",
    "vaccine efficacy": "The percentage reduction in disease incidence among vaccinated individuals (Chapter 10, p. 213).",
    "validity": "The extent to which a study measures what it intends (Chapter 5, p. 94).",
    "validity of measurement": "The accuracy of a measurement in reflecting the intended construct (Chapter 5, p. 94).",
    "validity_and_reliability": "The accuracy and consistency of measurements in studies (Chapter 5, p. 94–135).",
    "variable": "A characteristic or measurement that varies across individuals (Chapter 11, p. 233).",
    "variance": "A measure of data variability, the square of standard deviation (Chapter 11, p. 233).",
    "vector": "An organism (e.g., mosquito) transmitting an infectious agent (Chapter 2, p. 43).",
    "vehicle": "An inanimate source (e.g., food, water) transmitting disease (Chapter 2, p. 43).",
    "vehicle transmission": "Disease spread through contaminated objects or substances (Chapter 2, p. 43).",
    "vehicle-borne transmission": "Synonymous with vehicle transmission, via contaminated sources (Chapter 2, p. 43).",
    "virulence": "The severity of disease caused by an infectious agent (Chapter 2, p. 35).",
    "vital statistics": "Data on births, deaths, and other vital events (Chapter 4, p. 80).",
    "volunteer bias": "Bias where volunteers differ from non-volunteers, affecting generalizability (Chapter 15, p. 303).",
    "vulnerable population": "Groups at higher risk of disease due to social or biological factors (Chapter 19, p. 392).",
    "web of causation": "A model of multiple interacting factors causing disease (Chapter 14, p. 285).",
    "years lived with disability": "A measure of disease burden for time spent with reduced health (Chapter 4, p. 87).",
    "years of life lost (yll)": "A measure of premature mortality, weighted by years lost (Chapter 4, p. 87).",
    "years of potential life lost": "A measure of premature mortality before a standard age (Chapter 4, p. 87).",
    "zoonosis": "A disease transmitted from animals to humans, e.g., rabies (Chapter 2, p. 43).",
    "z-score": "A measure of how many standard deviations a value is from the mean (Chapter 11, p. 233).",
};
// This line makes the KNOWLEDGE_BASE object available to other files that import it.
module.exports = KNOWLEDGE_BASE;
