// A dictionary of epidemiology terms and their definitions, converted from the Python bot.
const KNOWLEDGE_BASE = {
      "accuracy": "The degree to which a measurement, or an estimate based on measurements, represents the true value of the attribute that is being measured.",
    "active immunity": "Resistance developed in response to stimulus by an antigen (infecting agent or vaccine) and usually characterized by the presence of antibody produced by the host.",
    "active surveillance": "A surveillance system where public health authorities actively seek out cases of disease, often through direct contact with healthcare providers or population surveys.",
    "adjusted rate": "A rate that has been statistically modified to remove the effect of a confounding factor (e.g., age-adjusted mortality rate).",
    "age-adjusted mortality rate": "A mortality rate statistically modified to eliminate the effect of different age distributions in the different populations, allowing for fairer comparisons.",
    "age-specific mortality rate": "A mortality rate limited to a particular age group. The numerator is the number of deaths in that age group; the denominator is the number of persons in that age group in the population.",
    "agent": "An **Agent** is a factor that is essential for a disease, chronic conditions, or injury to occur. Examples of agents include microorganisms, chemical substances, forms of radiation, and, in the case of injury, physical force.",
    "alpha error": "See Type I Error.",
    "analytic epidemiology": "**Analytic Epidemiology** is the aspect of epidemiology concerned with why and how a health problem occurs. It uses comparison groups to provide baseline data so that associations between exposures and outcomes can be quantified and hypotheses about the cause of the problem can be tested.",
    "analytic study": "A comparative study intended to identify and quantify associations, test hypotheses, and identify causes. Common types are cohort study and case-control study.",
    "applied epidemiology": "The application or practice of epidemiology to address public health issues, often in real-world settings.",
    "association": "**Association** is the statistical relationship between two or more events, characteristics, or other variables; does not necessarily imply causation.",
    "attack rate": "A type of incidence rate used in outbreak investigations, representing the proportion of a group that experiences an outcome or disease among those exposed. Formula: (Number of new cases in a population during an outbreak / Total population at risk) * 100%.",
    "attributable fraction (exposed)": "The proportion of disease among the exposed that could be attributed to the exposure. Formula: (Risk in Exposed - Risk in Unexposed) / Risk in Exposed, or (RR - 1) / RR.",
    "attributable risk (ar)": "The absolute amount of disease risk (incidence) in the exposed group that is directly attributable to the exposure; also known as Risk Difference. Formula: Incidence in Exposed Group - Incidence in Unexposed Group.",
    "autonomy": "An ethical principle emphasizing respect for individuals' decisions and choices regarding their own health and participation in research.",
    "background rate": "The usual or expected occurrence of a disease in a population in the absence of a specific exposure or intervention.",
    "basic reproductive number (r0)": "The average number of secondary cases produced by one infected individual in a completely susceptible population. If R0 > 1, an epidemic can occur.",
    "bayes' theorem": "A mathematical formula used to calculate the probability of an event based on prior knowledge of conditions that might be related to the event, often applied to predictive values of diagnostic tests. Formula: P(A|B) = [P(B|A) * P(A)] / P(B).",
    "bell-shaped curve": "A symmetrical curve that represents the normal distribution of data, where most values cluster around the mean.",
    "beneficence": "An ethical principle requiring that research and public health interventions maximize benefits and minimize harm to participants or populations.",
    "berkson's bias": "A type of selection bias that can occur in hospital-based case-control studies, where hospital admission rates for both the exposure and the disease are affected by a common factor, leading to a spurious association.",
    "beta error": "See Type II Error.",
    "bias": "Systematic error in a study that results in an incorrect estimate of the association between exposure and outcome.",
    "blinding (masking)": "A procedure in which the participants and/or investigators are kept unaware of the treatment assignment to prevent bias. Can be single, double, or triple.",
    "biological plausibility": "A Bradford Hill criterion for causality, suggesting that the observed association makes sense in the context of current biological and medical knowledge.",
    "biostatistics": "The application of statistical methods to biological and health-related data, essential for analyzing and interpreting epidemiological studies.",
    "bootstrapping": "A resampling technique used to estimate the sampling distribution of a statistic by repeatedly drawing samples with replacement from the observed data.",
    "bradford hill criteria": "A set of nine criteria proposed by Sir Austin Bradford Hill to provide a framework for assessing causality from observed associations: Temporality, Strength, Consistency, Biological Plausibility, Coherence, Specificity, Dose-Response, Reversibility, Analogy.",
    "burden of disease": "The impact of a health problem in an area measured by financial cost, mortality, morbidity, or other indicators.",
    "case": "An individual who meets the case definition for a particular disease or health condition.",
    "case-control study": "An observational study that compares individuals with a disease (cases) to individuals without the disease (controls) to identify factors that may have contributed to the disease.",
    "case-crossover study": "A study design where each case serves as their own control, comparing exposure during a hazard period to exposure during a control period in the same individual. Useful for transient exposures.",
    "case definition": "A set of diagnostic criteria that must be fulfilled for an individual to be regarded as a case of a particular disease for surveillance and outbreak investigation purposes.",
    "case-fatality rate": "The proportion of persons with a particular condition (e.g., patients) who die from that condition. Formula: (Number of deaths from a specific disease / Total number of cases of that disease) * 100%.",
    "case series": "A descriptive study that tracks a small group of patients with a similar diagnosis or treatment, providing insights into disease characteristics or treatment effects without a control group.",
    "case report": "A descriptive study that details the medical history and diagnosis of a single patient, often highlighting unusual or novel findings.",
    "causality": "The relationship between a cause and its effect. In epidemiology, establishing causation is complex and often relies on criteria like Bradford Hill's criteria.",
    "cause, component": "A factor that contributes to a sufficient cause. A sufficient cause is typically composed of several component causes.",
    "cause, necessary": "A causal factor that must be present for a disease or other health problem to occur. Without it, the disease cannot occur.",
    "cause, sufficient": "A factor or collection of factors whose presence is always followed by the occurrence of a particular health problem. It guarantees the outcome.",
    "censoring": "In survival analysis, when the exact time of an event is not known for some individuals (e.g., lost to follow-up, study ends before event occurs).",
    "chain of infection": "A model describing the elements necessary for infectious disease transmission: infectious agent, reservoir, portal of exit, mode of transmission, portal of entry, and susceptible host.",
    "chi-square test": "A statistical test used to determine if there is a significant association between two categorical variables.",
    "chronic disease": "A disease that is long-lasting or recurrent, often with a slow onset and long duration (e.g., heart disease, diabetes).",
    "clinical disease": "A disease that has been manifested by its symptoms and features.",
    "clinical significance": "The practical importance of a finding, regardless of its statistical significance.",
    "clinical trial": "A type of experimental study conducted in a clinical setting, often to evaluate the efficacy and safety of new treatments or interventions.",
    "cluster": "An aggregation of cases of a disease, injury, or other health condition in a circumscribed area during a particular period without regard to whether the number of cases is more than expected.",
    "coherence": "A Bradford Hill criterion for causality, suggesting that the observed association should not conflict with generally known facts of the natural history and biology of the disease.",
    "cohort": "A well-defined group of people who have had a common experience or exposure and who are then followed up for the incidence of new diseases or events.",
    "cohort study": "An observational study that follows groups of individuals (cohorts) over time to compare disease incidence in exposed versus unexposed groups.",
    "common source outbreak": "An outbreak that results from a group of people being exposed to the same harmful influence (e.g., contaminated food or water) at a single point in time or over a period.",
    "community trial": "An experimental study where the intervention is applied to entire communities rather than individuals.",
    "concordance": "The degree of agreement between two or more measurements or observers.",
    "confidence interval (ci)": "A range of values that is likely to contain the true population parameter with a certain level of confidence (e.g., 95% CI). Formula for a Proportion: p ± Z * √[p(1-p)/n]. Formula for a Mean: x̄ ± Z * (σ/√n).",
    "confounding": "A situation in which a measure of the effect of an exposure on risk of disease is distorted because of the association of exposure with other factor(s) that influence the outcome.",
    "confounding by indication": "A type of confounding that occurs in observational studies when the reason for receiving a treatment (or exposure) is itself a risk factor for the outcome.",
    "consistency": "A Bradford Hill criterion for causality, suggesting that similar findings across different studies and populations strengthen the likelihood of a causal relationship.",
    "contagious": "Capable of being transmitted from one person to another by contact or close proximity.",
    "contact tracing": "The process of identifying persons who may have come into contact with an infected person and subsequently monitoring them for symptoms.",
    "continuous variable": "A variable that can take any value within a given range (e.g., height, weight, blood pressure).",
    "control group": "The group in an experimental study that does not receive the intervention or receives a placebo, serving as a baseline for comparison.",
    "correlation": "A statistical measure that expresses the extent to which two variables are linearly related (meaning they change together at a constant rate).",
    "cox proportional hazards regression": "A statistical model used in survival analysis to examine the relationship between predictor variables and the time until an event occurs, while accounting for censoring. Yields Hazard Ratios.",
    "crude rate": "A rate that has not been adjusted for any factor, such as age, sex, or race.",
    "crude mortality rate": "The total number of deaths in a population during a specified period divided by the mid-period population. Formula: (Total deaths / Mid-period population) * 10^n.",
    "cross-sectional study": "An observational study that measures exposure and outcome simultaneously at a single point in time, providing a snapshot of the health status of a population.",
    "crossover trial": "An experimental design where participants receive a sequence of different treatments, with each participant serving as their own control.",
    "cumulative incidence": "The proportion of new cases of a disease occurring in a population at risk over a specified period. Formula: (Number of new cases / Number of people at risk at the beginning of the period).",
    "dalys (disability-adjusted life years)": "A measure of overall disease burden, expressed as the number of years lost due to ill-health, disability, or early death. Formula: Years of Life Lost (YLL) + Years Lived with Disability (YLD).",
    "data cleaning": "The process of detecting and correcting (or removing) corrupt or inaccurate records from a record set, table, or database.",
    "data quality": "The overall utility of a dataset as a function of its accuracy, completeness, reliability, and timeliness.",
    "dependent variable": "A variable that may be predicted by or caused by one or more other variables, called independent variables; the outcome variable.",
    "descriptive epidemiology": "Gathering, organizing, and summarizing data on 'person' (Who is ill?), 'time' (When did they become ill?), and 'place' (Where could they have been exposed to the illness?).",
    "determinant": "Any factor that brings about change in a health condition or in other specified characteristics.",
    "diagnostic test": "A medical test performed to confirm or rule out the presence of a disease in an individual who has symptoms.",
    "differential misclassification": "A type of information bias where the misclassification of exposure or outcome differs between study groups, which can bias the measure of association either towards or away from the null.",
    "direct standardization": "A method of adjusting rates to a standard population's age structure to allow for fairer comparisons between populations.",
    "direct transmission": "The immediate transfer of an agent from a reservoir to a susceptible host by direct contact or droplet spread.",
    "discrete variable": "A variable that can only take on a finite number of values or a countably infinite number of values (e.g., number of children, number of disease episodes).",
    "disease determinants": "Factors that influence the occurrence of disease or other health-related events. These can include genetic, environmental, social, behavioral, and other factors.",
    "disease distribution": "Refers to how disease is patterned in a population according to person, place, and time.",
    "disease surveillance": "The ongoing systematic collection, analysis, interpretation, and dissemination of health data essential to the planning, implementation, and evaluation of public health practice.",
    "dose-response relationship": "A relationship in which a change in amount, intensity, or duration of exposure is associated with a change in risk of a health outcome. A Bradford Hill criterion.",
    "double-blinding": "A type of blinding where neither the participant nor the investigator knows the treatment assignment.",
    "ecological fallacy": "An error in reasoning that occurs when inferences about individuals are made from data that describes groups.",
    "ecological study": "A study in which the units of analysis are populations or groups of people, rather than individuals. Often used to generate hypotheses.",
    "effectiveness": "The degree to which an intervention or program produces the intended or expected results under real-world conditions.",
    "effect modification": "When the magnitude of the effect of an exposure on an outcome differs depending on the level of a third variable (the effect modifier). Unlike confounding, it is a true biological phenomenon.",
    "efficacy": "The degree to which an intervention or program produces the intended or expected results under ideal conditions.",
    "efficiency": "The cost-benefit or cost-effectiveness of an intervention or program.",
    "endemic": "The constant presence of a disease or infectious agent within a given geographic area or population group.",
    "environmental epidemiology": "A subfield of epidemiology that studies the effects of environmental exposures (e.g., pollution, toxins) on human health.",
    "environment": "All external factors, other than the host and agent, that influence health (e.g., climate, sanitation, social conditions).",
    "epidemic": "The occurrence of cases of an illness, specific health-related behavior, or other health-related events clearly in excess of normal expectancy in a community or region.",
    "epidemic curve": "A graphical representation of the number of cases of a disease by date of onset, used to visualize the course of an epidemic.",
    "epidemiology": "The study of the distribution and determinants of health-related states or events in specified populations, and the application of this study to the control of health problems.",
    "etiologic": "Referring to the cause or origin of a disease.",
    "evidence-based public health": "The process of integrating science-based interventions with community preferences to improve the health of populations.",
    "excess risk": "The absolute difference in risk between an exposed group and an unexposed group (synonymous with Risk Difference or Attributable Risk).",
    "experimental study": "A study in which the investigator controls the exposure, typically by assigning participants to intervention or control groups (e.g., Randomized Controlled Trial).",
    "external validity (generalizability)": "The extent to which the findings of a study can be applied to other populations, settings, and times beyond those directly studied.",
    "false negative": "A test result that indicates a person does not have a disease when they actually do.",
    "false positive": "A test result that indicates a person has a disease when they actually do not.",
    "feasibility study": "A small-scale preliminary study conducted to evaluate the practicality of an intervention or research procedure.",
    "field trial": "A type of experimental study conducted among the general population to evaluate interventions that prevent disease or improve health.",
    "fomite": "An inanimate object or substance that is capable of transmitting infectious organisms from one individual to another (e.g., contaminated doorknob, clothing).",
    "frequency distribution": "A table or graph that displays the number of times each value or range of values appears in a dataset.",
    "generation time": "The time between when an individual is infected, and when that individual infects someone else.",
    "genetic epidemiology": "A subfield of epidemiology that studies the role of genetic factors and gene-environment interactions in disease causation and distribution.",
    "gold standard": "The best available diagnostic test or method for determining the true disease status, used as a reference to evaluate new tests.",
    "hazard ratio (hr)": "A measure of effect in survival analysis, representing the ratio of the hazard rates (instantaneous risk of an event) for two groups.",
    "healthy worker effect": "A type of selection bias where employed populations tend to have lower mortality rates than the general population because severely ill or disabled individuals are less likely to be employed.",
    "herd immunity": "The resistance to the spread of a contagious disease within a population that results if a sufficiently high proportion of individuals are immune to the disease, especially through vaccination.",
    "host": "A person or organism that can be infected by an agent that causes disease.",
    "hypothesis": "A supposition, arrived at from observation or reflection, that leads to testable predictions.",
    "hypothesis testing": "A statistical method used to determine if there is enough evidence in a sample data to infer that a certain condition is true for the entire population.",
    "iatrogenic disease": "A disease or condition caused by medical examination or treatment.",
    "immunity": "The state of being resistant to a particular infectious disease, typically by the presence of antibodies or sensitized white blood cells.",
    "incidence": "The rate at which new cases of a disease occur in a population at risk over a specified period.",
    "incidence rate ratio": "The ratio of the incidence rate in an exposed group to the incidence rate in an unexposed group. Formula: Incidence Rate in Exposed Group / Incidence Rate in Unexposed Group.",
    "incubation period": "The time from exposure to a disease to when the first signs or symptoms of the disease occur.",
    "independent variable": "A variable that may predict or cause fluctuation in a dependent variable; the exposure variable.",
    "index case": "The first case of a disease identified in an epidemic or outbreak.",
    "indirect standardization": "A method of adjusting rates used when age-specific rates for the study population are unstable or unavailable, often used to calculate Standardized Mortality Ratios (SMRs).",
    "indirect transmission": "Transfer through intermediaries such as airborne particles, inanimate objects, or vectors.",
    "individual-level data": "Data collected from individual persons, used in most analytic epidemiological studies.",
    "induction period": "The time required for a specific cause to produce disease; the interval from causal action to disease initiation.",
    "infectious agent": "Organisms like bacteria, viruses, or fungi that can cause disease by multiplying in a susceptible host.",
    "infectious disease epidemiology": "A subfield of epidemiology that focuses on the patterns, causes, and control of infectious diseases.",
    "infectivity": "The ability of an agent to enter, survive, and multiply in the host; the proportion of exposed people who become infected.",
    "informed consent": "A process by which a person voluntarily confirms his or her willingness to participate in a particular trial, after having been informed of all aspects of the trial that are relevant to the participant's decision to participate.",
    "information bias": "A systematic error that arises from systematic differences in the way data on exposure or outcome are obtained from the study groups.",
    "institutional review board (irb)": "A committee established to review and approve research involving human subjects. Its primary purpose is to protect the rights and welfare of human subjects.",
    "intention-to-treat (itt) analysis": "An analysis of randomized controlled trials where participants are analyzed in the groups to which they were originally randomized, regardless of whether they completed the intervention or switched groups. Preserves the benefits of randomization.",
    "internal validity": "The degree to which the results of a study are free from bias and confounding, and therefore accurately reflect the true relationship between exposure and outcome in the study population.",
    "interviewer bias": "A type of information bias where an interviewer's knowledge of a participant's disease status or exposure status influences the way they ask questions or record responses.",
    "interval variable": "A numerical variable where the order and exact differences between values are known, but there is no true zero point (e.g., temperature in Celsius or Fahrenheit).",
    "isolation": "The separation of sick people with a contagious disease from people who are not sick.",
    "justice": "An ethical principle requiring fair distribution of the burdens and benefits of research and public health interventions.",
    "kaplan-meier curve": "A non-parametric statistic used to estimate the survival function from lifetime data, often used in survival analysis to visualize event-free survival over time.",
    "kappa statistic": "A measure of inter-rater reliability for categorical items, indicating the agreement between two or more raters beyond what would be expected by chance.",
    "latent period": "The time from infection until being infectious, or the time from exposure to biological onset of disease; for non-infectious diseases, the period between exposure and disease manifestation.",
    "lead time bias": "A type of bias in screening programs where early detection of disease by screening gives the false impression of increased survival, simply because the disease was detected earlier in its course.",
    "length time bias": "A type of bias in screening programs where screening tests are more likely to detect slowly progressing, less aggressive forms of a disease, leading to an overestimation of the benefits of screening.",
    "levels of prevention": "Categorization of public health actions based on the stage of disease: Primary (preventing disease), Secondary (early detection), Tertiary (reducing impact).",
    "likelihood ratio": "A measure used in diagnostic testing that combines sensitivity and specificity to assess how much a test result changes the probability of disease. Positive LR = Sensitivity / (1 - Specificity); Negative LR = (1 - Sensitivity) / Specificity.",
    "life course epidemiology": "A field that studies the long-term effects of physical and social exposures during gestation, childhood, adolescence, and young adulthood on health and disease risk in later life.",
    "life expectancy": "The average number of years a person is expected to live based on current mortality rates.",
    "life table": "A statistical table showing the probability of a person at a particular age dying before their next birthday.",
    "linear regression": "A statistical model used to predict a continuous outcome variable based on one or more predictor variables.",
    "logistic regression": "A statistical model used to predict a binary outcome (e.g., presence/absence of disease) based on one or more predictor variables. Yields odds ratios.",
    "longitudinal study": "A study that follows the same group of individuals over a period of time, collecting data at multiple points.",
    "loss to follow-up bias": "A type of selection bias that occurs in cohort studies when participants who are lost to follow-up differ systematically from those who remain in the study, leading to biased results.",
    "maternal mortality rate": "The number of maternal deaths per 100,000 live births or per 100,000 women of reproductive age.",
    "matching": "A method used in study design to control for confounding by selecting study participants so that exposed and unexposed groups (or cases and controls) are similar with respect to potential confounders.",
    "mean": "The arithmetic average of a set of numbers. Formula: Sum of all values / Number of values.",
    "measures of central tendency": "Statistical measures that describe the center or typical value of a dataset: Mean, Median, and Mode.",
    "measures of dispersion": "Statistical measures that describe the spread or variability of a dataset: Range, Variance, and Standard Deviation.",
    "measures of disease frequency": "Quantify how often a disease occurs in a population, including incidence and prevalence.",
    "measures of association": "Quantify the strength of the relationship between an exposure and an outcome, such as Relative Risk and Odds Ratio.",
    "measures of impact": "Epidemiologic measures that quantify the potential public health impact of removing an exposure or implementing an intervention (e.g., Attributable Risk, Population Attributable Risk).",
    "median": "The middle value in a numerically ordered dataset. It is less affected by outliers than the mean.",
    "meta-analysis": "A statistical method for combining the results of multiple independent studies to derive a single, more precise estimate of an effect.",
    "misclassification bias": "A type of information bias that occurs when exposure or outcome status is incorrectly categorized.",
    "mixed outbreak": "An outbreak that has features of both common source and propagated outbreaks, often starting with a common exposure followed by person-to-person transmission.",
    "mode": "The value that appears most frequently in a dataset.",
    "morbidity": "Any departure, subjective or objective, from a state of physiological or psychological well-being. Often refers to illness or disease.",
    "mortality": "Refers to death.",
    "multivariable regression": "Statistical methods (e.g., linear, logistic, Cox regression) that allow for the simultaneous adjustment for multiple confounding variables.",
    "natural history of disease": "The progression of a disease in an individual over time, in the absence of treatment or intervention. It describes the stages from susceptibility to recovery, disability, or death.",
    "negative predictive value (npv)": "The probability that an individual with a negative test result actually does not have the disease (True Negatives / All Negative Test Results). Formula: True Negatives / (True Negatives + False Negatives).",
    "neonatal mortality rate": "The number of deaths among infants less than 28 days old per 1,000 live births.",
    "nested case-control study": "A case-control study conducted within an existing cohort, where cases and controls are drawn from the same cohort, often using stored biological samples.",
    "nominal variable": "A categorical variable where categories have no inherent order or ranking (e.g., blood type, race).",
    "non-differential misclassification": "A type of information bias where the misclassification of exposure or outcome occurs equally in all study groups, typically biasing the measure of association towards the null (underestimating the true effect).",
    "non-maleficence": "An ethical principle that requires doing no harm.",
    "non-response bias": "A type of selection bias that occurs when individuals who do not participate in a study differ systematically from those who do participate.",
    "null hypothesis (h0)": "A statement that there is no association between an exposure and an outcome, or no difference between groups.",
    "number needed to harm (nnh)": "The average number of patients who need to be exposed to a risk factor for one additional patient to be harmed (experience an adverse outcome) compared to a control group. Formula: 1 / Absolute Risk Increase.",
    "number needed to treat (nnt)": "The average number of patients who need to be treated with an intervention for one additional patient to benefit (avoid an adverse outcome) compared to a control group. Formula: 1 / Absolute Risk Reduction.",
    "observational study": "A study in which the investigator observes the exposure and outcome without intervening or assigning exposure (e.g., cohort, case-control, cross-sectional).",
    "odds ratio (or)": "A measure of association used in case-control studies, representing the ratio of the odds of exposure among cases to the odds of exposure among controls. Formula: (a*d) / (b*c) from a 2x2 table.",
    "one-sided test": "A statistical hypothesis test in which the alternative hypothesis is stated in a specific direction (e.g., exposure increases risk).",
    "operational definition": "A clear, concise definition of a measure or variable that specifies how it will be measured or observed in a study.",
    "ordinal variable": "A categorical variable where categories have a natural order or ranking, but the difference between categories may not be equal (e.g., disease stage: mild, moderate, severe).",
    "outbreak": "The occurrence of cases of a disease or other health-related events clearly in excess of normal expectancy in a localized area or specific group.",
    "overdiagnosis bias": "A type of bias in screening programs where screening detects diseases that would never have caused symptoms or death, leading to unnecessary treatment and inflated survival statistics.",
    "p-value": "The probability of observing a result as extreme as, or more extreme than, the one observed, assuming the null hypothesis is true. A small p-value (typically <0.05) suggests evidence against the null hypothesis.",
    "pandemic": "An epidemic occurring worldwide, or over a very wide area, crossing international boundaries, and usually affecting a large number of people.",
    "passive immunity": "Short-term immunity that results from the introduction of antibodies from another person or animal (e.g., maternal antibodies passed to a fetus).",
    "passive surveillance": "A surveillance system where health care providers or laboratories report cases of disease to public health authorities on a routine basis.",
    "pathogenesis": "The mechanism by which a cause or etiological agent produces disease.",
    "pathogenicity": "The proportion of infected individuals who develop clinical disease.",
    "per-protocol analysis": "An analysis of randomized controlled trials that includes only those participants who completed the intervention exactly as planned. Can be subject to bias.",
    "period prevalence": "The proportion of individuals in a population who have a disease or health condition over a specified period of time. Formula: (Number of existing cases during period / Average population during period) * 10^n.",
    "person-time": "A measurement combining persons and time as the denominator in incidence and mortality rates, used when individuals are at risk for varying periods.",
    "pilot study": "A small-scale preliminary study conducted to evaluate the feasibility, time, cost, adverse events, and improve upon the study design prior to performance of a full-scale research project.",
    "placebo": "An inert substance or treatment given to a control group in an experimental study to account for the placebo effect.",
    "placebo effect": "A beneficial effect produced by a placebo drug or treatment, which cannot be attributed to the properties of the placebo itself, and must therefore be due to the patient's belief in that treatment.",
    "point prevalence": "The proportion of individuals in a population who have a disease or health condition at a specific point in time. Formula: (Number of existing cases at a point in time / Total population at that point in time) * 10^n.",
    "poisson regression": "A statistical model used for count data or incidence rates, often when the outcome is a count of events over a period.",
    "population": "The total number of inhabitants of a given area or country, or in sampling, the units from which the sample is drawn.",
    "population attributable fraction (paf)": "The proportion of disease incidence in the total population that is attributable to a specific exposure. It reflects the potential reduction in disease if the exposure were eliminated from the population. Formula: (Incidence in Total Population - Incidence in Unexposed Group) / Incidence in Total Population, or [Pe * (RR-1)] / [Pe * (RR-1) + 1] where Pe is prevalence of exposure.",
    "population attributable risk (par)": "The absolute amount of disease risk in the total population that can be attributed to the exposure. Formula: Incidence in Total Population - Incidence in Unexposed Group.",
    "population pyramid": "A graphical representation of the age and sex composition of a population.",
    "portal of entry": "The pathway by which an infectious agent enters a susceptible host.",
    "portal of exit": "The pathway by which an infectious agent leaves the reservoir.",
    "positive predictive value (ppv)": "The probability that an individual with a positive test result actually has the disease (True Positives / All Positive Test Results). Formula: True Positives / (True Positives + False Positives).",
    "post-neonatal mortality rate": "The number of deaths among infants aged 28 days to less than 1 year per 1,000 live births.",
    "power (statistical power)": "The probability of correctly rejecting a false null hypothesis (i.e., detecting an effect if one truly exists). Formula: 1 - Type II Error (beta).",
    "precision": "The quality of being sharply defined or stated; the consistency of a measurement, inversely related to random error.",
    "prevalence": "The proportion of individuals in a population who have a disease or health condition at a specific point in time or over a specified period.",
    "prevalence odds ratio": "The odds ratio calculated from a cross-sectional study, used to estimate the association between exposure and prevalent disease.",
    "primary data": "Data collected specifically for the research question at hand (e.g., through surveys, clinical exams).",
    "primary infection": "The infection that introduces a pathogen into a population.",
    "primary prevention": "Aims to prevent disease before it occurs (e.g., vaccination, health education, lifestyle changes).",
    "propagated outbreak": "An outbreak that spreads from person to person, often characterized by a series of progressively taller peaks in the epidemic curve.",
    "proportion": "A type of ratio in which the numerator is included in the denominator; often expressed as a percentage.",
    "proportionate mortality": "The proportion of total deaths from a specific cause compared to all deaths. Formula: (Number of deaths from a specific cause / Total deaths from all causes) * 100%.",
    "prospective cohort study": "A cohort study where participants are enrolled and followed forward in time to observe the development of outcomes.",
    "public health intervention": "Any planned effort to prevent disease, promote health, or protect the public from health threats.",
    "qalys (quality-adjusted life years)": "A measure of disease burden, including both the quality and the quantity of life lived, where years are weighted by health utility. Formula: Sum of (Years of Life * Utility Value) for each period of time.",
    "quarantine": "The separation and restriction of movement of well persons who have been exposed to a contagious disease to see if they become sick.",
    "quasi-experimental study": "A study design that resembles an experimental study but lacks random assignment to intervention groups.",
    "random error": "Error that arises from chance and is not systematic. It affects the precision of a measurement, and can be reduced by increasing sample size.",
    "randomization": "The process of assigning participants to study groups (e.g., intervention or control) by chance, to ensure comparability between groups and control for confounding in experimental studies.",
    "range": "The difference between the highest and lowest values in a dataset.",
    "rate": "A measure of the frequency with which an event occurs in a defined population over a specified period of time.",
    "rate ratio": "The ratio of two rates, often used to compare incidence rates between exposed and unexposed groups. Formula: Incidence Rate in Exposed Group / Incidence Rate in Unexposed Group.",
    "ratio": "The value obtained by dividing one quantity by another; the numerator is not necessarily included in the denominator.",
    "ratio variable": "A numerical variable where the order, exact differences, and true zero point are all known (e.g., height, weight, age).",
    "recall bias": "A systematic error that occurs in retrospective studies when participants do not remember past exposures accurately, often differing between cases and controls.",
    "regression analysis": "A statistical method used to model the relationship between a dependent variable and one or more independent variables.",
    "relative risk (rr)": "A measure of association used in cohort studies, representing the ratio of the incidence of disease in the exposed group to the incidence in the unexposed group. Formula: [a/(a+b)] / [c/(c+d)] from a 2x2 table.",
    "reliability (reproducibility)": "The consistency of a test's results when repeated under the same conditions or by different observers.",
    "reporting bias": "The selective reporting or suppression of research findings, often based on the direction or significance of the results.",
    "representativeness": "The degree to which a sample or study population accurately reflects the characteristics of the larger population from which it was drawn, crucial for external validity.",
    "reservoir": "The habitat (human, animal, or environmental) in which an infectious agent normally lives, grows, and multiplies.",
    "residual confounding": "Confounding that remains after adjustment for confounding variables in a study, due to unmeasured confounders, imprecise measurement of confounders, or incorrect categorization of confounders.",
    "resistance": "The ability of a host to withstand infection or the effects of an infectious agent.",
    "restriction": "A method used in study design to control for confounding by limiting the study population to individuals who are homogeneous with respect to a confounding variable.",
    "retrospective cohort study": "A cohort study that uses historical data to reconstruct a cohort and follow them forward in time to observe outcomes.",
    "risk": "The probability that an individual will be affected by or die from illness/injury in a certain time/age span.",
    "risk difference": "The absolute difference in risk between an exposed group and an unexposed group. Formula: Incidence in Exposed Group - Incidence in Unexposed Group.",
    "risk factor": "A characteristic or exposure that is associated with an increased probability of developing a disease or adverse health outcome.",
    "sample": "A subset of a population selected for study.",
    "sample size": "The number of individuals or units included in a study, determined by statistical power considerations.",
    "sampling": "The process of selecting a subset of individuals from a larger population for a study.",
    "sampling error": "The error that arises when a sample is used to estimate a characteristic of the entire population.",
    "screening": "The presumptive identification of unrecognized disease or defects by the application of tests, examinations, or other procedures that can be applied rapidly.",
    "secondary attack rate": "The proportion of susceptible individuals who are exposed to a primary case and become infected. Formula: (Number of new cases among contacts of primary cases / Total number of susceptible contacts) * 100%.",
    "secondary data": "Data collected for purposes other than the current research question (e.g., vital statistics, medical records).",
    "secondary prevention": "Aims to detect disease early and prevent its progression (e.g., screening tests, early treatment).",
    "selection bias": "Occurs when there's a systematic difference between the characteristics of the people selected for a study and the characteristics of the people who are not selected, or when the study groups are selected improperly.",
    "sensitivity": "The ability of a test to correctly identify those with the disease (True Positives / All Diseased Individuals). Formula: True Positives / (True Positives + False Negatives).",
    "sensitivity analysis": "A method to assess how robust the study's conclusions are to different assumptions or potential sources of bias.",
    "sentinel surveillance": "A surveillance system that relies on a pre-selected network of reporting sites (e.g., specific clinics or hospitals) to collect data on particular health events.",
    "serial interval": "The time between when an individual experiences symptoms and when individuals infected by them experience symptoms.",
    "severity (virulence)": "The ability of a given pathogen to overcome defenses in the immune system and cause damage to the host; the proportion of persons with clinical disease who become severely ill or die.",
    "single-blinding": "A type of blinding where only the participant is unaware of the treatment assignment.",
    "social epidemiology": "A subfield of epidemiology that studies the social determinants of health and disease, including socioeconomic status, education, and social networks.",
    "social determinants of health": "The conditions in which people are born, grow, live, work, and age, and the wider set of forces and systems shaping the conditions of daily life (e.g., socioeconomic status, education, access to healthcare).",
    "specificity": "The ability of a test to correctly identify those without the disease (True Negatives / All Non-Diseased Individuals). Formula: True Negatives / (True Negatives + False Positives).",
    "sporadic": "A disease that occurs infrequently and irregularly, without any apparent pattern.",
    "standard deviation": "A measure of the amount of variation or dispersion of a set of values, calculated as the square root of the variance. Formula: √Variance.",
    "standard error": "A measure of the statistical accuracy of an estimate, equal to the standard deviation of the theoretical distribution of a large population of such estimates.",
    "standardized mortality ratio (smr)": "The ratio of the observed number of deaths in a study population to the expected number of deaths, often used in indirect standardization. Formula: Observed deaths / Expected deaths.",
    "statistical significance": "A result is statistically significant if it is unlikely to have occurred by chance, typically indicated by a p-value less than 0.05.",
    "strength of association": "A Bradford Hill criterion for causality, indicating that a stronger statistical association between exposure and outcome makes a causal relationship more likely.",
    "stratification": "A method to control for confounding by analyzing data within strata (subgroups) of the confounding variable, allowing for calculation of stratum-specific measures of association.",
    "sufficient-component cause model": "A conceptual model of causation where a 'sufficient cause' is a set of minimal conditions or events that inevitably produce disease, and 'component causes' are the individual factors within that set.",
    "surveillance": "The ongoing systematic collection, analysis, interpretation, and dissemination of health data essential to the planning, implementation, and evaluation of public health practice.",
    "susceptible host": "An individual or environment that can be infected by an agent due to lack of resistance.",
    "syndromic surveillance": "A surveillance system that uses health-related data that precede diagnosis and signal a sufficient probability of a case or an outbreak to warrant further public health response.",
    "systematic error": "Error that is not due to chance, but rather to a consistent bias in measurement or study design. It affects the accuracy of a measurement.",
    "temporality": "A criterion for causality stating that the cause must precede the effect in time.",
    "tertiary prevention": "Aims to reduce the impact of an existing disease and improve quality of life (e.g., rehabilitation, chronic disease management).",
    "transmissibility": "The ease with which an infectious agent is passed from an infected host to another susceptible host.",
    "true negative": "A test result that correctly indicates a person does not have a disease.",
    "true positive": "A test result that correctly indicates a person has a disease.",
    "t-test": "A statistical test used to compare the means of two groups to determine if they are significantly different.",
    "two-sided test": "A statistical hypothesis test in which the alternative hypothesis does not specify a direction (e.g., exposure is associated with risk, but not whether it increases or decreases it).",
    "type i error (alpha error)": "The error of rejecting a true null hypothesis (false positive). The probability of making a Type I error is denoted by alpha (α), typically set at 0.05.",
    "type ii error (beta error)": "The error of failing to reject a false null hypothesis (false negative). The probability of making a Type II error is denoted by beta (β).",
    "unbiased estimate": "An estimate of a population parameter that, on average, equals the true value of the parameter.",
    "under-reporting": "A common issue in surveillance where not all cases of a disease are reported to public health authorities.",
    "validity": "The degree to which a measurement actually measures or detects what it is supposed to measure (accuracy).",
    "variable": "Any characteristic or attribute that can be measured or observed and can take on different values.",
    "variance": "A measure of the dispersion of a set of values, calculated as the average of the squared differences from the mean. Formula: Σ(xᵢ - μ)² / N (for population) or Σ(xᵢ - x̄)² / (n-1) (for sample).",
    "vector": "An animate intermediary in the indirect transmission of an agent that carries the agent from a reservoir to a susceptible host (e.g., mosquito for malaria).",
    "vehicle": "An inanimate intermediary in the indirect transmission of an agent that serves as a means by which the agent is transported from a reservoir to a susceptible host (e.g., contaminated food, water, or air).",
    "virulence": "The proportion of persons with clinical disease who, after becoming infected, become severely ill or die.",
    "vital statistics": "Systematically tabulated information about births, marriages, divorces, and deaths, based on registration of these vital events.",
    "volunteer bias": "A type of selection bias that occurs when individuals who volunteer for a study differ systematically from those who do not volunteer.",
    "web of causation": "A conceptual model that illustrates the complex interplay of multiple factors (causes) that contribute to the occurrence of a disease, rather than a single cause.",
    "years of life lost (yll)": "A component of DALYs, representing the years of life lost due to premature mortality.",
    "years lived with disability (yld)": "A component of DALYs, representing the years lived with any disability, weighted by the severity of the disability.",
    "years of potential life lost (ypll)": "A measure of premature mortality, calculated as the sum of the differences between a predetermined age at death (e.g., 75 years) and the age at death for individuals who died prematurely. Formula: Sum of (Predetermined Age at Death - Age at Death) for individuals who died prematurely.",
    "z-score": "A statistical measure that describes a value's relationship to the mean of a group of values, measured in terms of standard deviations from the mean. Formula: (x - μ) / σ.",
    "zoonosis": "An infectious disease that is transmissible from animals to humans."
};

// This line makes the KNOWLEDGE_BASE object available to other files that import it.
module.exports = KNOWLEDGE_BASE;
